# Generated by Django 4.1.2 on 2022-10-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentwork',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
