# Generated by Django 4.1.2 on 2022-10-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentwork',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
