# Generated by Django 4.1.2 on 2022-10-10 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_recentwork_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('comment', models.TextField()),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='app.recentwork')),
            ],
        ),
    ]
